databases:
  - name: odnix-db
    databaseName: odnix
    user: odnix
    plan: free
    postgresMajorVersion: "18"

services:
  - type: web
    name: odnix-backend
    env: python
    buildCommand: "bash build.sh"
    startCommand: "daphne odnix.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: odnix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
