# Generated by Django 5.2.4 on 2025-12-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_postreport_savedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='omzos/')),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omzos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmzoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('omzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.omzo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omzo_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OmzoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('omzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chat.omzo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_omzos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('omzo', 'user')},
            },
        ),
    ]
