# Generated by Django 5.0 on 2025-12-19 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_omzo_omzocomment_omzolike'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmzoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment or Bullying'), ('violence', 'Violence or Threats'), ('hate_speech', 'Hate Speech'), ('false_info', 'False Information'), ('copyright', 'Copyright Infringement'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('omzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.omzo')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omzo_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'omzo')},
            },
        ),
    ]
