# Generated by Django 5.0 on 2025-12-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_add_expanded_theme_choices"),
        ("chat", "0009_omzo_omzocomment_omzolike"),
    ]

    operations = []
