# Generated by Django 5.0 on 2025-12-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_omzoreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('copyright', 'Copyright Infringement'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment or Bullying'), ('violence', 'Violence or Threats'), ('hate_speech', 'Hate Speech'), ('false_info', 'False Information'), ('other', 'Other')], max_length=20),
        ),
    ]
