# Generated by Django 5.0 on 2025-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_omzo_audio_mute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='copyright_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio Copyright'), ('content', 'Content Copyright'), ('both', 'Both Audio and Content Copyright')], help_text='Whether the copyright is for audio or content', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='omzoreport',
            name='copyright_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio Copyright'), ('content', 'Content Copyright'), ('both', 'Both Audio and Content Copyright')], help_text='Whether the copyright is for audio or content', max_length=10, null=True),
        ),
    ]
