# Generated by Django 5.0 on 2026-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_profileview_p2psignal_chat_p2psig_created_47dfe0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_transform',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
