# Generated by Django 5.0 on 2026-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_story_image_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text_size',
            field=models.FloatField(default=22.0),
        ),
    ]
