# Generated by Django 5.0 on 2026-01-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_story_text_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
