# Generated by Django 5.0 on 2026-01-12 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_rename_tweet_to_scribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dislike",
            name="scribe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scribe_dislikes",
                to="chat.scribe",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="scribe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scribe_likes",
                to="chat.scribe",
            ),
        ),
        migrations.AlterField(
            model_name="mention",
            name="mentioned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scribe_mentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scribe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="scribe_images/"),
        ),
        migrations.AlterField(
            model_name="scribe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scribes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scribehashtag",
            name="hashtag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scribes",
                to="chat.hashtag",
            ),
        ),
        migrations.AlterField(
            model_name="scribehashtag",
            name="scribe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scribe_hashtags",
                to="chat.scribe",
            ),
        ),
    ]
