# Generated by Django 5.0 on 2026-01-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_add_notification_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="scribe",
            name="original_omzo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="chat.omzo",
            ),
        ),
        migrations.AddField(
            model_name="scribe",
            name="original_scribe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="chat.scribe",
            ),
        ),
        migrations.AddField(
            model_name="scribe",
            name="original_story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="chat.story",
            ),
        ),
    ]
