# Generated by Django 5.0 on 2026-01-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_scribe_original_omzo_scribe_original_scribe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scribe",
            name="quote_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="chat.scribe",
            ),
        ),
    ]
