# Generated by Django 5.0 on 2026-01-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0032_scribe_quote_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="shared_from_story",
            field=models.ForeignKey(
                blank=True,
                help_text="Original story if this is a repost",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_reposts",
                to="chat.story",
            ),
        ),
    ]
