# Generated by Django 5.0 on 2026-01-18 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0033_story_shared_from_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional message sent with the shared content",
                        max_length=500,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("scribe", "Scribe"),
                            ("omzo", "Omzo"),
                            ("story", "Story"),
                            ("text", "Text Message"),
                        ],
                        default="scribe",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When request was accepted/declined",
                        null=True,
                    ),
                ),
                (
                    "created_chat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chat created when request was accepted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_request",
                        to="chat.chat",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User receiving the shared content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_chat_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who initiated the share",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_omzo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shared omzo if content_type='omzo'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_requests",
                        to="chat.omzo",
                    ),
                ),
                (
                    "shared_scribe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shared scribe if content_type='scribe'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_requests",
                        to="chat.scribe",
                    ),
                ),
                (
                    "shared_story",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shared story if content_type='story'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_requests",
                        to="chat.story",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status", "-created_at"],
                        name="chat_chatre_recipie_19608e_idx",
                    ),
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="chat_chatre_sender__a68a90_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chatrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "pending"),
                    models.Q(("shared_scribe", None), _negated=True),
                ),
                fields=("sender", "recipient", "shared_scribe"),
                name="unique_pending_scribe_share_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "pending"),
                    models.Q(("shared_omzo", None), _negated=True),
                ),
                fields=("sender", "recipient", "shared_omzo"),
                name="unique_pending_omzo_share_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "pending"),
                    models.Q(("shared_story", None), _negated=True),
                ),
                fields=("sender", "recipient", "shared_story"),
                name="unique_pending_story_share_request",
            ),
        ),
    ]
