# Generated by Django 5.0 on 2026-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_chat_request_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
