# Generated by Django 5.0 on 2026-01-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_add_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
