# Generated by Django 5.0 on 2026-02-04 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOmzoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('omzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='chat.omzo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_omzo_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='chat_savedo_user_id_ec6fc5_idx')],
                'unique_together': {('user', 'omzo')},
            },
        ),
        migrations.CreateModel(
            name='SavedScribeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='chat.scribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scribe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='chat_saveds_user_id_46fd97_idx')],
                'unique_together': {('user', 'scribe')},
            },
        ),
    ]
