# Generated by Django 5.0 on 2026-02-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_savedomzoitem_savedscribeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story_reply',
            field=models.ForeignKey(blank=True, help_text='Story that this message is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_replies', to='chat.story'),
        ),
    ]
