# Generated by Django 5.0 on 2026-02-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_message_story_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_omzo',
            field=models.ForeignKey(blank=True, help_text='Omzo shared in this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_messages', to='chat.omzo'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_scribe',
            field=models.ForeignKey(blank=True, help_text='Scribe shared in this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_messages', to='chat.scribe'),
        ),
    ]
