# Generated by Django 5.0 on 2026-02-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_message_shared_omzo_message_shared_scribe'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['one_time', 'consumed_at'], name='msg_onetime_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'one_time'], name='msg_chat_onetime_idx'),
        ),
    ]
